### ISSUE TITLE
[BUG]: Discussion link broken in README

### ISSUE THREAD

**Issue by peschee** [Matsuuu/web-component-devtools#17]
**Describe the bug**

The discussion link seems broken in README.

**To Reproduce**
1. Go to 'Github Repository URL'
2. Click on 'Join here: https://join.slack.com/share/zt-sffg0x76-2t1QoM1JWXrzfEbL9XP2_w'
3. See error

**Expected behavior**
Slack channel invitation is successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/63866/126270433-60445b6c-a6e9-4838-89c5-28d9617cc838.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91.0.x

**Comment by Matsuuu** [comment]
Hi,

A good catch! Fixed now :)
