### ISSUE TITLE
[BUG]: CEM resolution does not take base tags into accound

### ISSUE THREAD

**Issue by Westbrook** [Matsuuu/web-component-devtools#19]
**Describe the bug**
If a site it delivered with a `<base>` tag, CEM resolution look in the wrong directory for a `custom-elements.json` file resulting in a 404.

**To Reproduce**
1. Go to https://opensource.adobe.com/spectrum-web-components/components/sidenav
2. Inspect
3. See 404

**Expected behavior**
When available, CEM should be resolved in the directory the app is served from.

**Comment by Matsuuu** [comment]
Fixed [here](https://github.com/Matsuuu/web-component-devtools/commit/9d0bc7efdd90b1ac8e569c2b5b342b171e794f00).

However the example link has a base of `https://opensource.adobe.com/spectrum-web-components` making the CEM url `https://opensource.adobe.com/spectrum-web-components/custom-elements.json`, which currently still returns 404

**Comment by Westbrook** [comment]
Great. I don’t have a file there, correct. I didn’t want to do any work on it if it wasn’t going to work. I’ll take a look at how we can get that to be so!
