### ISSUE TITLE
[Feature Request]: Add "Scroll into view" functionality

### ISSUE THREAD

**Issue by shaal** [Matsuuu/web-component-devtools#21]
**Which browser are you using?**
Edge Chromium

**Is your feature request related to a problem? Please describe.**
I can scroll through a long webcomponents list easily, but I want to see where and how it appears on the website and I need to manually scroll the web page and find it.

**Describe the solution you'd like**
Similar to how in the browser's DevTools, I can go to "Elements" tab, right-click on an element, and choose "Scroll into view", I would like to add that option when I look in WCDT, 
![image](https://user-images.githubusercontent.com/22901/127332953-189b02ac-3004-4b0c-a723-6f11c250b936.png)
I wish I could right-click an element (or have a button next to it?) that has that functionality, and instead of manually find the component on the page somewhere, it will scroll the page so I can see it right there.

**Describe alternatives you've considered**

**Additional context**

**Comment by Matsuuu** [comment]
Thanks for the suggestion!

Funnily enough, the original version of WCDT had this functionality built in by default, but I removed it before shipping the first version :D

I'll have to look into a nice UI/UX way of implementing this but will definitely do this for the next update!

**Comment by shaal** [comment]
👍

**Comment by Matsuuu** [comment]
https://github.com/Matsuuu/web-component-devtools/commit/f3b07bf4be51eb6e69cfcc3fc2677549e3e20040 Implemented here. Will maybe work on some UX.

What do you think, should it also select the target element in the devtools?

**Comment by Matsuuu** [comment]
Tested around and made it so that it also selects the list item when you decide to scroll to it. Felt like the best UX.

This will ship in v0.1.6. Will close this for now
