### ISSUE TITLE
Sort Properties and Methods 

### ISSUE THREAD

**Issue by Danny-Engelman** [Matsuuu/web-component-devtools#30]
Maybe sort the list, and collapse "private" ones usually marked with an underscore.

![](https://i.imgur.com/Zng89vo.png)

**Comment by Matsuuu** [comment]
I've been looking to sort the props alphabetically and by category.

Making an opinionated choice to mark underscore props as private , and therefore behind a collapsible option is something I'll have to consider.

Maybe behind a checkbox for those who want this

**Comment by Danny-Engelman** [comment]
And I just noticed... those properties are **not** capitalized in my source code.

Great tool BTW, I was working on something similar, shelved that project.

**Comment by Matsuuu** [comment]
Yeah I capitalized them for clarity. It's on the chopping block whether I'll keep them that way.

Also, thanks ! 🤗 Spread the word!

**Comment by Danny-Engelman** [comment]
I will be the first to spread the word not to use this tool, if it displays incorrect code info.

Display the method names (and everything else) as-is.

<hr>

Here is the list of properties I record:

* qid - Component ID, probably only useful for testing
* depth - DOM level 0=root
* host  - getRootNode().Host (link to element)
* parent - localName (link to element)
* localName 
* id 
* childNodes 
* children 
* shadowRoot 
* styles 
* slots 
* shadowRoot_childNodes 
* shadowRoot_children
