### ISSUE TITLE
Less whitespace listing the CE nodeName/localName, include all outerHTML

### ISSUE THREAD

**Issue by Danny-Engelman** [Matsuuu/web-component-devtools#31]
I ran the Inspector on https://cardmeister.github.io/

![](https://i.imgur.com/6goxId4.png)

That is a lot of useless whitespace.

Isn't one column with the outerHTML (now abreviated on the right) enough?

The Custom Element name by itself serves no real purpose.

**Comment by Matsuuu** [comment]
The current approach is taken from how other devtools do it (react, angular).  This will therefore be held this way
