### ISSUE TITLE
Inspectors lists String values of default parameters

### ISSUE THREAD

**Issue by Danny-Engelman** [Matsuuu/web-component-devtools#33]
I ran the Inspector on: https://pie-meister.github.io/

![](https://i.imgur.com/3tZjWgv.png)

#### My method:

```
 svg(
     root, 
     colors = (this.getAttribute("stroke") || "#3c3,#c33,#33c,#cc3,#c3c,#3cc").split(","), 
     pull = ~~this.getAttribute("pull"), 
     t = 0, 
     pathLength = 0
) 
```

#### Issues

* You are listing the String values

* parameters do not have to be **formal** parameters, they can also be used to define variables and functions private to the function. As used in ``pathLength = 0``. 

* On minified files you won't get the properly named parameters

**Comment by Matsuuu** [comment]
Having function calls as params is not something that really is in the scope. It already turns `true` and `false`. Turning json objects to actual json objects is also shipping in the next patch.
