### ISSUE TITLE
[Feature Request]: support custom elements that have no definition

### ISSUE THREAD

**Issue by e111077** [Matsuuu/web-component-devtools#42]
**Which browser are you using?**

Chrome

**Is your feature request related to a problem? Please describe.**

Often times I have a web component and it isn't rendering, and often the root of the problem is that it is not defined (no call to `customElements.define`).

**Describe the solution you'd like**

Show elements with hyphens (`-`) in their name that are not defined in the custom element registry and note that they are not yet defined.

**Additional context**

Many times undefined custom elements are intentional e.g. lazy loading upgrade, SSR partial hydration, or just using placeholder component names like in Angular.

**Comment by Matsuuu** [comment]
Great idea! Currently I do checks on elements with hyphens, and then check if they are present in the encosing window's customElements object.

It would be beneficial in a dev environment to list out elements not yet upgraded/defined as you said, and I'll definitely look into implementing this as a feature, maybe even into the next release.

```
Many times undefined custom elements are intentional e.g. lazy loading upgrade, SSR partial hydration, or just using placeholder component names like in Angular.
```

If you have example projects/sites that implement these practices, please do share them

**Comment by Matsuuu** [comment]
There's now features for showing unregistered components and also displaying an icon when they are hydrated. I'll be closing this now
