### ISSUE TITLE
[BUG]: Certain apps cause an infinite loop

### ISSUE THREAD

**Issue by e111077** [Matsuuu/web-component-devtools#43]
**Describe the bug**

Certain apps like Angular cause an infinite loop when you open WC dev tools.

**To Reproduce**
1. Go to angular.io
2. Open WC dev tools
3. select the first element you see

**Expected behavior**

It not make my PC sound like it's mining crypto

**Desktop (please complete the following information):**
 - OS: Mac OS 11.6
 - Browser Chrome
 - Version 94

**Additional context**

They're not in the CE registry

**Comment by Matsuuu** [comment]
The angular context seemed to be quite a hefty object to iterate through for analysis and was causing the issues. I added a preliminary compatibility layer for angular [here](https://github.com/Matsuuu/web-component-devtools/commit/1dcb2db1d97338f91116392a28928ad33f20e400), but in it's current state it doesn't quite list everything we would maybe want it to list.

I'm not experienced with angular, nor do I have a demo project to test the tooling on, so if you have a demo project with say, 2 kinds of properties, a few attributes and a few events, I'd love to test / develop the angular support against it.

But the preliminary fix should resolve the infinite loop problem, and will be shipped in the next release.

Closing this as it's been resolved, but if you have a test site with angular components as described above, please do share it with me via github/slack/twitter :)
