### ISSUE TITLE
Strange GCP issue

### ISSUE THREAD

**Issue by smashah** [Matsuuu/web-component-devtools#57]
For some reason my GCP Logs Explorer was seizing up and taking out all google tabs in my chrome. I disabled all my extensions one by one to resolve the issue and apparently something about this extension is causing that strange behaviour.

Repro:
1. Install & enable web component devtools extension
2. Go to firebase console => functions => check the logs of one of your functions
3. It will then take you to GCP Logs Explorer.
4. Click "Run Query"
5. It will start loading then freeze.

Chrome Version: 108.0.5359.124 (Official Build) (arm64) on Apple Macbook M1 Pro.

Not sure what is causing this behaviour but I thought I'd let you know & for reference for anybody else.

Thanks

**Comment by Matsuuu** [comment]
Heya @smashah 

Thanks for the step by step repro of this. This is definitely something that shouldn't be happening.

Some follow-up questions:

- Did you have your devtools open on any of the tabs?
- Did you have Web Component DevTools open on any of those tabs?


Sorry to hear that it happens for you, I'll try to work out a fix ASAP

**Comment by smashah** [comment]
> Did you have your devtools open on any of the tabs?

Most likely not/not that I recall - I have many tabs open so it's possible that I left devtools open on one of them. 

> Did you have Web Component DevTools open on any of those tabs?

Nope

**Comment by smashah** [comment]
Let me know if you're not able to repro so I can look further into it/gather more evidence

**Comment by Matsuuu** [comment]
Finally found some time to look at this and I'm pretty sure I found the issue and fixed it. GCP sites have some janky Iframes that caused the querying part of the analyzer go haywire.

The 0.2.1 version should ship on chrome in the coming days and fix this. Please re-open this if it isn't fixed after the update.
