### ISSUE TITLE
Web Components in Storybook aren't being found

### ISSUE THREAD

**Issue by mabry1985** [Matsuuu/web-component-devtools#7]
I'm guessing this is an iFrame issue, but when I search through our design system in Storybook using the extension I'm not seeing the components. It looks like I'm getting some of the Storybook components themselves, but not our components.

![Screen Shot 2021-06-30 at 8 40 52 AM](https://user-images.githubusercontent.com/31560031/123990765-ebcb2d80-d97e-11eb-852a-5156e748af7a.png)

I'm seeing this warning in the console `[WebComponentDevTools]: Message send missed. Connection not found.`

**Comment by Matsuuu** [comment]
Hey! Thanks for reporting a bug even in the beta.

I did some fiddling with iframes and storybook earlier and got it working against a open-wc storybook.

What's your setup? Do you have a link or a repo?

**Comment by mabry1985** [comment]
My team is very excited about this extension and I will definitely be playing with it as much as possible, so I'll let you know if I break anything else.

This is the repo for the design system that's currently a WIP

https://github.com/phase2/outline

**Comment by mabry1985** [comment]
This may be just an issue when running local. I was able to get it to work on our GH page deploy

http://outline.phase2tech.com/?path=/story/atoms-image--image-with-caption&globals=measureEnabled:false

**Comment by Matsuuu** [comment]
Thanks for the links and info! Glad to hear you're as excited about this as I am! 

I'll check this out asap as I get home

**Comment by Matsuuu** [comment]
Looking at your project, a little off topic but you should update to using this analyzer https://github.com/open-wc/custom-elements-manifest/tree/master/packages/analyzer

**Comment by Matsuuu** [comment]
Heya.

There was a small bug introduced today in how I find package.json's and custom-elements.json's.

Fixed it and it seems to work at least in my end 
![image](https://user-images.githubusercontent.com/16068444/123998321-0bdc0a80-d9da-11eb-8c5b-5b295baba155.png)

**Comment by mabry1985** [comment]
Oh beautiful, got my local updated and it works as planned. Thanks for the help, looking forward to seeing what's next! 

Closing this issue.
