### ISSUE TITLE
The case of multiple meta tags

### ISSUE THREAD

**Issue by Matsuuu** [Matsuuu/web-component-devtools#9]
As discussed in the commit discussions, https://github.com/Matsuuu/web-component-devtools/commit/fcfc874b8651523e4e59475af21c25e3b5776eea

"""
It's possible the manifest will be located on another domain/subdomain, such as when a library is delivered via CDN. Because of that, the origin probably shouldn't be appended to the path if the path is absolute.

Thinking further ahead, and possibly outside the project's initial scope, it will be useful to allow multiple manifest files, especially on end user websites where more than one web component/library is being consumed. My suggestion for this would be separate meta tags instead of concatenating URLs into a one. (This will make it dead simple for libs to document how to get the tag in an end user website: e.g. "just add this tag to your page".)

<meta name="custom-elements-manifest" content="lib1/custom-elements.json">
<meta name="custom-elements-manifest" content="lib2/custom-elements.json">
<meta name="custom-elements-manifest" content="https://example.com/custom-elements.json">
"""

A implementation should be created to support a series of manifests, if this becomes a part of the schema.

Thinking about the schema itself, should the package.json's "customElements" be a array too?

**Comment by claviska** [comment]
> Thinking about the schema itself, should the package.json's "customElements" be a array too?

I don't have a strong opinion on this. One library => one manifest keeps things simple, but that probably won't work well for monorepos where each component is packaged independently but a single manifest is generated for all of them.

**Comment by thepassle** [comment]
> monorepos where each component is packaged independently but a single manifest is generated for all of them.

imo monorepos should generate a CEM per package and have each package ship a CEM, as opposed to having one 'global' CEM

**Comment by claviska** [comment]
👆 I agree and would be totally fine with such a requirement. To play devil's advocate, does it make sense to allow an array for collections that aggregate components from various libs, or would generating a new manifest be desirable here as well?

I'm probably thinking too far ahead. Aside from these, I can't think of any other reasons someone would require an array here. 🤷🏻‍♂️

**Comment by Matsuuu** [comment]
Closing this for now since if this discussion needs to be continued, it'd probably be better to do so in the cem repo
